name: airsolo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3



#------  PACKAGES  ------#
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  iconsax: ^0.0.8
  get_storage: ^2.1.1
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  hugeicons: ^0.0.7
  carousel_slider: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0



#------ ./ PACKAGES END ------#
flutter:
  uses-material-design: true


#------  LOCAL ASSETS ------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/icons/
    - assets/images/verify/
    - assets/images/banners/
    - assets/logo/
    - assets/images/items/


#------  LOCAL FONTS ------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

 
