name: airsolo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3



#------  PACKAGES  ------#
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  iconsax: ^0.0.8
  get_storage: ^2.1.1
  get: ^4.6.6

  
  




dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0



#------ ./ PACKAGES END ------#
flutter:
  uses-material-design: true


#------  LOCAL ASSETS ------#
  assets:
    - assets/


#------  LOCAL FONTS ------#

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/poppin

 
