name: airsolo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3



#------  PACKAGES  ------#
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  iconsax: ^0.0.8
  get_storage: ^2.1.1
  get: ^4.7.2
  smooth_page_indicator: ^1.2.0+3
  hugeicons: ^0.0.7
  carousel_slider: ^5.0.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3

  # FireBase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3
  country_picker: ^2.0.27
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  device_info_plus: ^11.3.3
  badges: ^3.1.2
  shimmer: ^3.0.0
  payhere_mobilesdk_flutter: ^3.2.0
  webview_flutter: ^4.11.0
  google_maps_flutter_ios: ^2.15.1
  google_maps_flutter: ^2.12.1
  printing: ^5.14.2
  pdf: ^3.11.3
  geolocator: ^14.0.0
  bottom_picker: ^3.0.0
  credit_card_input_form: ^2.3.0
  flutter_markdown: ^0.7.7
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  flutter_polyline_points: ^2.1.0
  google_places_autocomplete_text_field: ^1.1.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0



#------ ./ PACKAGES END ------#
flutter:
  uses-material-design: true


#------  LOCAL ASSETS ------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/icons/
    - assets/images/verify/
    - assets/images/banners/
    - assets/logo/
    - assets/images/items/
    - assets/images/user/
    - assets/images/animations/


#------  LOCAL FONTS ------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

 
