// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9lnW5D__WBCRsy44E5AokkKfOyAiyREc',
    appId: '1:792576944881:web:022cebab708fcaf839d750',
    messagingSenderId: '792576944881',
    projectId: 'airsolo',
    authDomain: 'airsolo.firebaseapp.com',
    storageBucket: 'airsolo.firebasestorage.app',
    measurementId: 'G-YW49L1JY79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauj8ZxF_eclQG919ILMkvlwddS7Xnb6I',
    appId: '1:792576944881:android:d83728ab77ed21d239d750',
    messagingSenderId: '792576944881',
    projectId: 'airsolo',
    storageBucket: 'airsolo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTQfjeJcccsU5eGlb-SVqn586nSRiQlTY',
    appId: '1:792576944881:ios:c069547d006b512039d750',
    messagingSenderId: '792576944881',
    projectId: 'airsolo',
    storageBucket: 'airsolo.firebasestorage.app',
    iosBundleId: 'com.example.airsolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTQfjeJcccsU5eGlb-SVqn586nSRiQlTY',
    appId: '1:792576944881:ios:c069547d006b512039d750',
    messagingSenderId: '792576944881',
    projectId: 'airsolo',
    storageBucket: 'airsolo.firebasestorage.app',
    iosBundleId: 'com.example.airsolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9lnW5D__WBCRsy44E5AokkKfOyAiyREc',
    appId: '1:792576944881:web:6f12b470a2dbf1d039d750',
    messagingSenderId: '792576944881',
    projectId: 'airsolo',
    authDomain: 'airsolo.firebaseapp.com',
    storageBucket: 'airsolo.firebasestorage.app',
    measurementId: 'G-SZRVP7MHCW',
  );
}
