import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';

List<Map<String, dynamic>> facilities = [
  {"name": "Wi-Fi", "icon": Iconsax.wifi},
  {"name": "A/C", "icon": Icons.ac_unit},
  {"name": "Restaurant", "icon": Icons.restaurant},
  {"name": "Swimming Pool", "icon": Icons.pool},
  {"name": "Parking", "icon": Icons.local_parking},
  {"name": "Gym", "icon": Icons.fitness_center},
  {"name": "Bar", "icon": Icons.local_bar},
  {"name": "TV", "icon": Icons.tv},
  {"name": "Room Service", "icon": Icons.room_service},
  {"name": "Laundry", "icon": Icons.local_laundry_service},
  {"name": "24/7 Reception", "icon": Icons.support_agent},
  {"name": "Security", "icon": Icons.security},
  {"name": "Spa & Wellness", "icon": Icons.spa},
  {"name": "Conference Room", "icon": Icons.meeting_room},
  {"name": "Business Center", "icon": Icons.business},
  {"name": "Pet Friendly", "icon": Icons.pets},
  {"name": "Non-Smoking ", "icon": Icons.smoke_free},
  {"name": "Airport Shuttle", "icon": Icons.local_taxi},
  {"name": "Breakfast", "icon": Icons.free_breakfast},
  {"name": "Mini Bar", "icon": Icons.local_drink},
  {"name": "Balcony", "icon": Icons.balcony},
  {"name": "Mountain View", "icon": Icons.terrain},
  {"name": "Sea View", "icon": Icons.waves},
  {"name": "Garden", "icon": Icons.nature},
  {"name": "BBQ Facilities", "icon": Icons.outdoor_grill},
  {"name": "Bicycle Rental", "icon": Icons.directions_bike},
  {"name": "Car Rental", "icon": Icons.car_rental},
  {"name": "EV Charging", "icon": Icons.electric_car},
  {"name": "Luggage Storage", "icon": Icons.luggage},
  {"name": "Library", "icon": Icons.local_library},
  {"name": "Hot Tub", "icon": Icons.hot_tub},
  {"name": "Sauna", "icon": Icons.wb_sunny},
  {"name": "Kids’ Play Area", "icon": Icons.child_care},
  {"name": "Tennis Court", "icon": Icons.sports_tennis},
  {"name": "Golf Course", "icon": Icons.sports_golf},
  {"name": "Casino", "icon": Icons.casino},
  {"name": "Karaoke", "icon": Icons.mic},
  {"name": "Live Music", "icon": Icons.music_note},
  {"name": "Fireplace", "icon": Icons.fireplace},
  {"name": "CCTV ", "icon": Icons.videocam},
  {"name": "Elevator", "icon": Icons.elevator},
  {"name": "First Aid Kit", "icon": Icons.medical_services},
  {"name": "Accessible Rooms", "icon": Icons.accessible},
  {"name": "Self Check-In", "icon": Icons.lock_open},
  {"name": "Late Check-Out", "icon": Icons.access_time},
  {"name": "Iron ", "icon": Icons.iron},
  {"name": "Shared Kitchen", "icon": Icons.kitchen},
  {"name": "Private Entrance", "icon": Icons.door_front_door},
  {"name": "Mosquito Net", "icon": Icons.bug_report},
  {"name": "Work Desk", "icon": Icons.work},
  {"name": "Hair Dryer", "icon": Iconsax.scissor},
  {"name": "Coffee Maker", "icon": Icons.coffee},
  {"name": "Microwave", "icon": Icons.microwave},
  {"name": "Toiletries", "icon": Icons.bathroom},
  {"name": "Extra Bed", "icon": Icons.bed},
  {"name": "Sofa Bed", "icon": Icons.weekend},
  {"name": "Smart TV", "icon": Icons.smart_display},
  {"name": "Game Room", "icon": Icons.sports_esports},
  {"name": "Tours & Activities", "icon": Icons.map},
];
